[window]
dimensions = { columns = 120, lines = 36 }
opacity = 0.95
decorations = "Full"

[font]
normal = { family = "GohuFont 14 Nerd Font", style = "Regular" }
size = 14

[colors.primary]
foreground = "#FFFFFF"
background = "#000000"

[colors.cursor]
text = "#ffffff"
#cursor = "#0060FF" # Blue
cursor = "#CC0000"

[selection]
save_to_clipboard = true

[keyboard]
bindings = [
    { key = "Up", mods = "Command", action = "ToggleMaximized" },
    { key = "Left", mods = "Alt", chars = "\u001BB" },
    { key = "Right", mods = "Alt", chars = "\u001BF" },
]
